public class SimpleCalculator {
//Define methods to perform basic Arithmetic Operations
//Method without Returntype and Parameters

    public void add(){
        //Defining Attributes
        Integer x=20, y= 10;
        
        //Performing Operations
        Integer z = x+y;
        
        //Display the result on log
        System.debug('Result of Addition: '+z);
    }
    
    //Method without Parameter and Returntype
    public void sub(){
        Integer x = 20, y=10;
        Integer z=x-y;
        System.debug('Result of Subtraction: '+z);
    }
    
    //Method without Parameter and Returntype
    public void multiply(){
        Integer x = 30, y=2;
        Integer z = x*y;
        System.debug('Result of Multiplication: '+z);
    }
    
    //Method without Parameter and Returntype
    public void divide(){
        Integer a = 20, b= 2;
        Integer c = a/b;
        System.debug('Result of Division: '+c);
    }
    
    //Method with Parameters and No Returntype(void)
    public void paraAdd(Integer a,Integer b){
		Integer c=a+b;
        System.debug('Result of Add with Parameter: '+c);
    }
    
    //Method with Parameter and Returntype
    public Integer paraSub(Integer i,Integer j){
        Integer num = i-j;
        return num;
    }
}
